[project]
name = "trial-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.51.0",
    "beir>=2.1.0",
    "faiss-cpu>=1.11.0",
    "fastmcp>=2.3.4",
    "nltk>=3.9.1",
    "rank-bm25>=0.2.2",
]
